runtime: python37

default_expiration: "0m"

handlers:
    
- url: /static
  static_dir: /app/static
  expiration: '0m'
  
- url: /
  static_files: app/static/index.html
  upload: app/static/index.html

  